name: Scheduled Rules

on:
  #  schedule:
  #    - cron: '1 0 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - uses: actions/checkout@v4
        with:
          ref: page
          path: page
      - name: Run rules
        run: python main/build.py > page/test/data.json

      - name: Change working directory
        run: cd page

      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add test/data.json
          git commit -m "Auto Build"
          git push